# Generated by Django 2.0.4 on 2018-04-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pmodel',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('mbin', models.BinaryField(null=True)),
                ('target', models.CharField(max_length=80)),
                ('explanatory', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '予測モデル',
                'verbose_name_plural': '予測モデル',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('race_dt', models.DateField(db_index=True, null=True)),
                ('place_id', models.CharField(max_length=2)),
                ('place_name', models.CharField(max_length=8)),
                ('days', models.IntegerField(null=True)),
                ('times', models.IntegerField(null=True)),
                ('round', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('type', models.CharField(max_length=16)),
                ('length', models.IntegerField(null=True)),
                ('weather', models.CharField(max_length=16)),
                ('condition', models.CharField(max_length=16)),
                ('head_count', models.IntegerField(null=True)),
                ('max_prize', models.FloatField(null=True)),
                ('odds_stdev', models.FloatField(null=True)),
                ('result_flg', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'レース',
                'verbose_name_plural': 'レース',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('key', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(null=True)),
                ('bracket', models.IntegerField(null=True)),
                ('horse_num', models.IntegerField(null=True)),
                ('horse_id', models.CharField(db_index=True, max_length=12)),
                ('horse_name', models.CharField(max_length=80)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField(null=True)),
                ('burden', models.FloatField(null=True)),
                ('jockey_id', models.CharField(max_length=10)),
                ('jockey_name', models.CharField(max_length=80)),
                ('finish_time', models.FloatField(null=True)),
                ('last3f_time', models.FloatField(null=True)),
                ('odds', models.FloatField(null=True)),
                ('odor', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('weight_diff', models.IntegerField(null=True)),
                ('trainer_id', models.CharField(max_length=10)),
                ('trainer_name', models.CharField(max_length=80)),
                ('owner_id', models.CharField(max_length=12)),
                ('owner_name', models.CharField(max_length=80)),
                ('prize', models.FloatField(null=True)),
                ('t3r_jockey', models.FloatField(null=True)),
                ('cnt_run', models.IntegerField(null=True)),
                ('t3r_horse', models.FloatField(null=True)),
                ('avg_ror', models.FloatField(null=True)),
                ('avg_prize', models.FloatField(null=True)),
                ('avg_last3f', models.FloatField(null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='umap.Race')),
            ],
            options={
                'verbose_name': '出走情報',
                'verbose_name_plural': '出走情報',
            },
        ),
        migrations.CreateModel(
            name='Expect',
            fields=[
                ('result',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='umap.Result')),
                ('rf_top3', models.NullBooleanField()),
            ],
            options={
                'verbose_name': '予測結果',
                'verbose_name_plural': '予測結果',
            },
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['race_dt'], name='umap_race_race_dt_f5c7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['horse_id'], name='umap_result_horse_i_bb6b70_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['jockey_id'], name='umap_result_jockey__b6d539_idx'),
        ),
    ]
