# Generated by Django 2.0.3 on 2018-03-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('race_dt', models.DateField(db_index=True, null=True)),
                ('place_id', models.CharField(max_length=2)),
                ('place_name', models.CharField(max_length=8)),
                ('days', models.IntegerField(null=True)),
                ('times', models.IntegerField(null=True)),
                ('round', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('type', models.CharField(max_length=16)),
                ('length', models.IntegerField(null=True)),
                ('weather', models.CharField(max_length=16)),
                ('condition', models.CharField(max_length=16)),
                ('head_count', models.IntegerField(null=True)),
                ('max_prize', models.FloatField(null=True)),
                ('odds_stdev', models.FloatField(null=True)),
                ('result_flg', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'レース',
                'verbose_name_plural': 'レース',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('key', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(null=True)),
                ('bracket', models.IntegerField(null=True)),
                ('horse_num', models.IntegerField(null=True)),
                ('horse_id', models.CharField(db_index=True, max_length=12)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField(null=True)),
                ('burden', models.FloatField(null=True)),
                ('jockey_id', models.CharField(max_length=10)),
                ('finish_time', models.FloatField(null=True)),
                ('last3f_time', models.FloatField(null=True)),
                ('odds', models.FloatField(null=True)),
                ('odor', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('weight_diff', models.IntegerField(null=True)),
                ('trainer_id', models.CharField(max_length=10)),
                ('owner_id', models.CharField(max_length=12)),
                ('prize', models.FloatField(null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='umap.Race')),
            ],
            options={
                'verbose_name': '出走情報',
                'verbose_name_plural': '出走情報',
            },
        ),
    ]
