# Generated by Django 2.0.4 on 2018-04-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='umap.Result')),
                ('top3_flg', models.IntegerField(null=True)),
                ('top3_ratio', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': '特徴',
                'verbose_name_plural': '特徴',
            },
        ),
    ]
